// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDujjjXzwKnSCcIODgjT49p2SzfvIOgP3Q',
    appId: '1:1026221178979:web:4098ac451f139e3d497856',
    messagingSenderId: '1026221178979',
    projectId: 'aquafilter-25608',
    authDomain: 'aquafilter-25608.firebaseapp.com',
    storageBucket: 'aquafilter-25608.firebasestorage.app',
    measurementId: 'G-3L8LC32MZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd9l0uOCpSDP4SpLcqKwJoJ4Lz5vrYOtY',
    appId: '1:1026221178979:android:97cbd7807f55a7fd497856',
    messagingSenderId: '1026221178979',
    projectId: 'aquafilter-25608',
    storageBucket: 'aquafilter-25608.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2VbumC0NQGwX3tyHPi9zKDfuTVbbrUuM',
    appId: '1:1026221178979:ios:a839d72a0cd2bb3e497856',
    messagingSenderId: '1026221178979',
    projectId: 'aquafilter-25608',
    storageBucket: 'aquafilter-25608.firebasestorage.app',
    iosBundleId: 'com.example.aquaFilter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2VbumC0NQGwX3tyHPi9zKDfuTVbbrUuM',
    appId: '1:1026221178979:ios:a839d72a0cd2bb3e497856',
    messagingSenderId: '1026221178979',
    projectId: 'aquafilter-25608',
    storageBucket: 'aquafilter-25608.firebasestorage.app',
    iosBundleId: 'com.example.aquaFilter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDujjjXzwKnSCcIODgjT49p2SzfvIOgP3Q',
    appId: '1:1026221178979:web:96d9be621fc9ce53497856',
    messagingSenderId: '1026221178979',
    projectId: 'aquafilter-25608',
    authDomain: 'aquafilter-25608.firebaseapp.com',
    storageBucket: 'aquafilter-25608.firebasestorage.app',
    measurementId: 'G-42LZBPL4MK',
  );
}
